# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.56.2",
      virtualbox__intnet: true
    web.vm.network "forwarded_port", guest: 22, host: 3002
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "forwarded_port", guest: 9113, host: 9002
    web.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub.host"
    web.vm.provision "file", source: "nginx-prometheus-exporter.service", destination: "nginx-prometheus-exporter.service"
    web.vm.provision "shell", path: "web_provision.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.network "private_network", ip: "192.168.56.3",
      virtualbox__intnet: true
    db.vm.network "forwarded_port", guest: 22, host: 3003
    db.vm.network "forwarded_port", guest: 9100, host: 9003
    db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub.host"
    db.vm.provision "shell", path: "db_provision.sh"
  end

  config.vm.define "monitor" do |monitor|
    monitor.vm.box = "ubuntu/bionic64"
    monitor.vm.network "private_network", ip: "192.168.56.4",
      virtualbox__intnet: true
    monitor.vm.network "forwarded_port", guest: 22, host: 3004
    monitor.vm.network "forwarded_port", guest: 9090, host: 9090
    monitor.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub.host"
    monitor.vm.provision "shell", path: "monitor_provision.sh"
  end
end
