services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  backend:
    build: .
    restart: always
    ports:
      - "80:5000"
    volumes:
      - ${PWD}/backend-my.cnf:/etc/my.cnf.d/custom.cnf
    develop:
      watch:
        - action: "sync"
          path: .
          target: /code
    depends_on:
      - db
